### PR TITLE
Synching all transaction types and creating accounts with authorityID

### PR DESCRIPTION
**Pull request by bbnickell**

### CODE REVIEW

**Comment by bbnickell** [comment]
@facing-n felt like this was a good time to merge this into the v2 main branch:

* Correctly syncs all transaction types
* Creates accounts and links the authorityId
* Lots of iterating and optimizing the logging output
* Upon startup, will not sync the universe and will only update transactions since the last block time. We'll add the cron that does the daily consistency check on all transactions.

Still need to identify a small number of missing transactions since I've been diffing the datasets form the prod transactions on chain with the ones syncing to my local database, but wanted to get this reviewed and merged in for a goal post check.

**Comment by bbnickell** [comment]
Following up on our discussion this morning, relevant to this PR for the new TransactionSyncer in Indexer v2: https://github.com/nina-protocol/nina-indexer/pull/736/

We're capturing ~97% of all transactions but currently we're missing a very small subset of transactions.

Here's a couple of specific examples of transactions that are not being captured, which can be identified by running the indexer and observing the console output:

```
2024-10-16T19:51:07.435Z: Fetched signature 314FSWp3TXfcA6YaAG1h7XFSBXZguSDryKzkA1HYRc9oAH7fxrCSdPENQ3zvGnYpdtD2MYoy4qnU8jpffuwgdNZ9
100|nina-indexer  | 2024-10-16T19:51:07.957Z: Warning: No relevant accounts found for transaction 2a6wjMHpJy1BCcFSYbbnQB2jQ6tv9spbbVMJCNZjb8zjL2eMHHdRe1jPJ1FbHhHVu33Nb3HZ1U7NtF2aXoZhRdFH
100|nina-indexer  | 2024-10-16T19:51:07.961Z: Warning: No relevant accounts found for transaction 5LkmLuGVRJzAPqso6TbciLQR4vUUuX8xEM9unHjCioM31PLbw7EJUzVDx1eGmjWMZ6Q2SoaxvjxE1NhXXtLDP6GZ
100|nina-indexer  | 2024-10-16T19:51:07.992Z: Inserted transaction 4YD615ZrrcGS6nxv3GoQ8wU6AvhdBmU6cqXca4WUYFCVFdSESf6txHy7d6Vpmp6CzUS3KRbn1jooKbuFTqJP4Ars
```

The relevant missing transactions can be evaluated on Solana Explorer:

https://solscan.io/tx/2a6wjMHpJy1BCcFSYbbnQB2jQ6tv9spbbVMJCNZjb8zjL2eMHHdRe1jPJ1FbHhHVu33Nb3HZ1U7NtF2aXoZhRdFH
https://solscan.io/tx/5LkmLuGVRJzAPqso6TbciLQR4vUUuX8xEM9unHjCioM31PLbw7EJUzVDx1eGmjWMZ6Q2SoaxvjxE1NhXXtLDP6GZ

As a result of not being able to parse these transactions, we're also not able to index the relevant accounts that are transacting. My first approach was to review the transaction parsing logic. getRelevantAccounts is unable to find any accounts associated with the transactions. The code to determine this is akin to v1 of the indexer where find the nina instruction and return the accounts:

```
getRelevantAccounts(txInfo) {
  const ninaInstruction = txInfo.transaction.message.instructions.find(
    i => i.programId.toBase58() === process.env.NINA_PROGRAM_ID
  );
  return ninaInstruction ? ninaInstruction.accounts : [];
}
```

My guess is that the way that we're trying to find the Nina Program ID is maybe too restrictive. I tried a few different ways around this and it made the indexing worse and lost more transactions.

Many of these transactions are in the "ReleasePurchase" category. We are obviously highly reliant on the log messages to determine the transaction type and extract the accounts. I think a better approach would be to look at the account lengths and match them up against the expected account lengths for each transaction type, but could definitely use your input here on examining the data structure and what has given us the most trouble in the past.

**Comment by facing-n** [comment]
Yeah - our Coinflow purchases happen through a separate CPI to a program that only handles Coinflow purchases so you have to look into the inner instructions - this is done in the old indexer here: https://github.com/nina-protocol/nina-indexer/blob/caad168b36aa688c3f41169de47dcfffa0e9b60b/indexer/processor.js#L475

**Comment by bbnickell** [comment]
@facing-n Okay we are synching all transactions as far as I can tell, I'm going to be writing a more thorough check tomorrow morning but we are not getting any more errors from parsing transactions in the log.

Interestingly, however we are actually synching about 400 more transactions in the new indexer that do not exist in the public indexer -- I'll be sending that data over to you directly. Worth individidually exploring those transactions.

**Comment by facing-n** [comment]
> @facing-n Okay we are synching all transactions as far as I can tell, I'm going to be writing a more thorough check tomorrow morning but we are not getting any more errors from parsing transactions in the log.
> 
> Interestingly, however we are actually synching about 400 more transactions in the new indexer that do not exist in the public indexer -- I'll be sending that data over to you directly. Worth individidually exploring those transactions.

yeah this is super interesting.  im guess that for some reason or another these txs hit an error getting created and were never indexed again.

the earliest is from before we were even live ([9/29/2021](https://explorer.solana.com/tx/3oeuRvKjiMaMbADNpJ2ZRXNUajqB4R7rAMdjsJjVjYrVjYuBe8FJoJGBf9FW87H8fnFApzvZd4giKg9TQDYsDrQG)) and the most recent is from [yesterday](https://explorer.solana.com/tx/4f7Z6a1SiE6yyig9xcGREeoiBSTMm1sB76HWC8ex2FN27xrgkggRgAzuDcXeXkUPjaCBSeNUpb6W2xMSgd3fmw2s).

> 90% are from the last 10 months.  My guess is that these failure might be coming from the callback step from `/api`.  Somethings about building or updating Hub and Release records.  

I think this is a good sign that we are catching these here and we should be on the lookout for complications once we start building and updating Hub and Release records.

**Review by facing-n — APPROVED** [review]

**Pull request merged**
